destination_research_task:
  description: >
    Research {destination} for {travel_season} travel: attractions, weather, transport, safety, visa/currency, local events.
  expected_output: >
    Structured research report with key facts for {destination} in {travel_season}.
  agent: travel_researcher

itinerary_planning_task:
  description: >
    Create {duration}-day itinerary for {destination} ({travel_season}) within {budget}.
    Include: exact addresses, Google Maps URLs (MUST use format: https://www.google.com/maps/search/?api=1&query=Location+Name+Address+with+plus+signs),
    hours, costs, transport routes.
  expected_output: >
    Day-by-day itinerary with locations, times, costs for {duration} days.
  agent: itinerary_planner

local_insights_task:
  description: >
    Provide insider knowledge for {destination} ({travel_season}): hidden gems, local restaurants,
    markets, cultural sites, neighborhoods, transport hubs - all with exact addresses and Google Maps URLs
    (MUST use format: https://www.google.com/maps/search/?api=1&query=Location+Name+Address+with+plus+signs).
  expected_output: >
    Local expert guide with insider tips and specific recommendations for {destination}.
  agent: local_expert

budget_analysis_task:
  description: >
    Create budget breakdown for {destination} ({travel_season}) within {budget}:
    accommodation, transport, food, activities, emergency fund, seasonal savings tips.
  expected_output: >
    Budget breakdown with cost estimates and money-saving tips for {duration} days.
  agent: budget_advisor

final_travel_plan_task:
  description: >
    Compile all research into comprehensive travel plan: executive summary, day-by-day itinerary,
    budget, local tips, emergency info, packing list.

    CRITICAL Google Maps URL Rules:
    - MUST use format: https://www.google.com/maps/search/?api=1&query=Location+Name+Full+Address
    - Replace ALL spaces with + signs
    - NO commas in the query parameter
    - NO /goo.gl/ links
    - NO maps.google.com format

    Example: https://www.google.com/maps/search/?api=1&query=Tokyo+Tower+4-2-8+Shibakoen+Minato+City+Tokyo+Japan

    Generate HTML version using HTMLGenerator tool.
  expected_output: >
    Complete travel guide document for {destination} as organized markdown.
  agent: itinerary_planner
